services:

  db1:
    image: postgres:14.1-alpine
    container_name: team3-db1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_one
    ports:
      - "5434:5432"
    volumes:
      - ./db1-init:/docker-entrypoint-initdb.d
      - db1-data:/var/lib/postgresql/data

  db2:
    image: postgres:14.1-alpine
    container_name: team3-db2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_two
    ports:
      - "5433:5432"
    volumes:
      - ./db2-init:/docker-entrypoint-initdb.d
      - db2-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: team3-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: team3-kafka-broker
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "29093:29092"
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: team3-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://team3-kafka-broker:9092,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  db1-data:
  db2-data:
